### ISSUE TITLE
Ordering Activity / search Activity by type.

### ISSUE THREAD

**Issue by LindaLawton** [maiera/gde-app#125]
I would like to be able to go though all of my activities the ones related to my tutorials and blog posts and add the comment count from my website.  But there are so many and it doesn't appear to be possible to figure out what is a post and what is a bug report.     Can we make this a little easier if i am going to have to update this manually once a month?

**Comment by SmokyBob** [comment]
Moved to the [new repo](https://github.com/GoogleDeveloperExperts/gde-app-web/issues/4)
