### ISSUE TITLE
Create dashboard views per product

### ISSUE THREAD

**Issue by maiera** [maiera/gde-app#163]
To make the GDE App more impactful inside Google, create a dashboard view for each product, so the Googlers in the given product area can see the number of different activities for their product only, and their impact.

Basically the same view as the overall dashboard, but filtered to only include a given product hashtag.

**Comment by SmokyBob** [comment]
Test version live on [points_to_firefly](https://gdetracking.gweb.io/hist/points_to_firefly/#/)

**Comment by patt0** [comment]
copied all entities from omega to firefly ... data up to date (07/1/2015)


Patrick Martinent

**Comment by SmokyBob** [comment]
Deployed in production
