### ISSUE TITLE
Update Avatar Builder to remove desaturation

### ISSUE THREAD

**Issue by rharter** [maiera/gde-app#171]
I don't use the GDE Avatar builder because, while I makes a nicely badged avatar, it desaturates my actual photo.  I understand that that might be done for color safety, but the most important part of my avatar is not the GDE logo, the most important part is me.

I would probably use it if it was updated to include the badge over my saturated photo, using the current translucent text protection.

**Comment by destil** [comment]
+1

**Comment by destil** [comment]
@reicek Can I use your builder somehow? Do you have some fork of the web running somewhere?

**Comment by SmokyBob** [comment]
Moved
