### ISSUE TITLE
what date to use for blog views, and how to update them

### ISSUE THREAD

**Issue by brucemcpherson** [maiera/gde-app#176]
I noticed that time based reporting is being done at a summary level, and I wondered how people were recording ongoing pageviews & +1's for existing activities. For example, I have a single entry for each topic on my site (which may consist of 20 or so individual pages), that has the date of when I first recorded it in the tracker.

Every now and then, I update each single topic's +1 & pageview counts (to date) from analytics to the new values. I don't create a new entry with, lets say, this month's views, since that doing that could overstate the number of activities (it's the same activity.. just additional impact information, and in some cases, additional blog posts in that topic). I don't really want to create a separate item for every blog post, (which is why I use the topic principle), and I certainly don't want to create a new entry each month - there are now about 700 pages with about 1m pageviews a year.

What is everyone else doing, and what should we be doing? Apologies if I missed guidance on this earlier.  My expectation is that I'll automate this at some point but I'd like to understand the details before embarking on that.

**Comment by SmokyBob** [comment]
Moved to new repo
