### ISSUE TITLE
Add raw_impact Charts and Tables

### ISSUE THREAD

**Issue by SmokyBob** [maiera/gde-app#189]
As requested during the GDE app sync call of 2014-12-11 before the total_impact, show the raw_impact.
The raw_impact is the sum of the data to calculate the total_impact but without the logarithmic functions applied.

**Comment by SmokyBob** [comment]
As discussed in #190 a new column `meta_impact` will be added to charts and tables , 'social_impact' will sum the current 3 columns `plusones`, `reshares` and `comments` and will be displayed instead.

**Comment by SmokyBob** [comment]
PR #193 implement the changes.
[Live Demo](https://gdetracking.gweb.io/hist/mauro/issue189/)

**Comment by patt0** [comment]
I think we need to mention the total impact, but still display it as a log
maybe????

The graphs become meaningless with this value I think.



Patrick Martinent

**Comment by SmokyBob** [comment]
@patt0 do you mean remove the `Total Impact` from the charts or show the Log(x) of metadata and social impact because otherwise the values of those two tends to be so big to make the `total_impact` invisible?

**Comment by patt0** [comment]
Yes I think we can make the visualisation much more interesting by having
two scales, one linear for which values such as activities logged and total
impact ( calc value ) will be ploted and on the other axix have a log scale
against which we can plot meta_impact and social_impact


Patrick Martinent

**Comment by SmokyBob** [comment]
Deployed Test version on [staging](https://10-dot-gdetracking.appspot.com/#/) but the staging api on firefly seems to not return raw metadata columns.
We can discuss if the new charts looks good (and other chart additions) during tomorrow's meeting (if needed I can switch the code to use the prod api in the staging site briefly to see meaningful data)

**Comment by patt0** [comment]
I am in Malaysia this week ... I will try to make the call.  Yes its
possible the latest code has not been pushed to staging.

I'll try to get connected, check and push in a couple of hours.

Best

**Comment by patt0** [comment]
I have updated the data from omega to firefly and we now get some values in
RAW, looks nice but I dont think they are correct tough.

I also pushed the latest code to firefly.


Patrick Martinent



On 18 February 2015 at 04:04, Patrick Martinent <patrick.martinent@gmail.com
> wrote:

> I am in Malaysia this week ... I will try to make the call.  Yes its
> possible the latest code has not been pushed to staging.
>
> I'll try to get connected, check and push in a couple of hours.
>
> Best
>

**Comment by SmokyBob** [comment]
... I should stop deploying things at night...
I've fixed the code in the source code and run the build job, but the
staging site is still responding with the old code... I'll check later.
