### ISSUE TITLE
cant edit data

### ISSUE THREAD

**Issue by brucemcpherson** [maiera/gde-app#195]
when i try to edit page views in existing items, i get the message only gde and admin can edit. I am logged in as normal.

**Comment by SmokyBob** [comment]
we removed the previously applied hack that used the `api_key` instead of Google + (client) & email (server) authentication during inserts and deletes, after a discussion with Ola about #133 (going to update that issue with the result of the discussion. TL;DR; provided email for the GDE directory and the email associated to the Google + account must be the same). 

Can you please look in the Dev Tools `Console` tab and post (or send me privately) the logs that looks like the following?
> GdeApp Backend API LOADED!
> plusLoginCtrl: metadata-ready received
> startCtrl: metadata-ready received
> event emitted
> Logged userId:117141236479651677751
> Logged email:mauro.solcia@gmail.com
> Welcome Mauro Solcia (Smokybob).
> You are a GDE!

I'll check and see if there is an issue in the account config

**Comment by brucemcpherson** [comment]
Hi Mauro

having timeout troubles this morning. not loading the app at all (times
out) on my chromebook. Will try on a mac or something later on and let you
know

 GET http://gdetracking.gweb.io/ net::ERR_CONNECTION_TIMED_OUT
 GET http://gdetracking.gweb.io/ net::ERR_CONNECTION_RESET

bruce

**Comment by brucemcpherson** [comment]
Working again on chromebook.

Seems to log me in correctly, but fails when i try to edit something

 GdeApp Backend API LOADED!
plusLoginCtrl.js:123 plusLoginCtrl: metadata-ready received
startCtrl.js:141 startCtrl: metadata-ready received
GdeTrackingApp.js:38 event emitted
plusLoginCtrl.js:89 Logged userId:112066118406610145134
plusLoginCtrl.js:90 Logged email:bruce@mcpher.com
plusLoginCtrl.js:24 Welcome Bruce Mcpherson.
plusLoginCtrl.js:40 You are a GDE!
GoLang.png:1 GET http://gdetracking.gweb.io/img/badges/GoLang.png 404 (Not
Found)
cb=gapi.loaded_0:99 POST
https://omega-keep-406.appspot.com/_ah/api/gdetracking/v1.0b2/activityRecord?alt=json
401 (Unauthorized)
myStatisticsCtrl.js:776 gdeTrackingAPI.activity_record.insert(DATA)
responded with Response Code: 401 - Only GDEs and admins may enter or
change data.
myStatisticsCtrl.js:777
{"resharers":0,"total_impact":4.02530586526477,"activity_link":"
http://ramblings.mcpher.com/Home/excelquirks/drivesdk","date_updated":null,"gplus_id":"112066118406610145134","activity_types":["#opensourcecode","#tutorial"],"comments":0,"post_date":"2015-02-01","deleted":false,"date_created":null,"gde_name":"Bruce
Mcpherson","product_groups":["#googleappsapi","#googleappsscript","#googledrive"],"plus_oners":30,"meta_impact":52,"activity_title":"Using
drive sdk with google apps script - all pages in
topic","social_impact":19,"id":"5183246660796416","metadata":[{"impact":98,"description":"Using
drive sdk with google apps script","title":"Using drive sdk with google
apps script","link":"http://ramblings.mcpher.com/Home/excelquirks/drivesdk
","type":"#tutorial","activity_group":"#content","$$hashKey":"1U6"},{"activity_group":"#opensourcecode","$$hashKey":"1U7"}],"kind":"gdetracking#activity_recordItem","gplus_posts":[]}


[image: Inline images 1]

**Comment by Scarygami** [comment]
Problem was that the front-end is using a new client-ID which wasn't in the list of allowed client IDs in the backend. I pushed an update to the backend and it should work again now.

Can you check again?

**Comment by brucemcpherson** [comment]
Gerwin .. great - thanks it works now.

bruce

**Comment by Scarygami** [comment]
Fixed with https://github.com/maiera/gde-app/commit/b700bc0fd9bf51c9afb0e8d8f16c5d3e7d44b39d

**Comment by SmokyBob** [comment]
Sorry about that, I've carelessly pushed that change.
About the timeouts... we unfortunately know and we are trying a different approach while keeping things as simple as possible

**Comment by brucemcpherson** [comment]
no problem. thanks for fixing it so quickly

**Comment by brucemcpherson** [comment]
Mauro

bad gateway (502) problems this morning, meaning that no components are
being loaded..

GET http://gdetracking.gweb.io/js/resources/angular-route.min.js
gdetracking.gweb.io/:27 GET
http://gdetracking.gweb.io/components/platform/platform.js
gdetracking.gweb.io/:19 GET
http://gdetracking.gweb.io/js/resources/angular.min.js
gdetracking.gweb.io/:28 GET
http://gdetracking.gweb.io/components/web-animations-js/web-animations.js
gdetracking.gweb.io/:18 GET
http://gdetracking.gweb.io/js/resources/jquery-2.1.0.min.js
gdetracking.gweb.io/:246 GET http://gdetracking.gweb.io/js/GdeTrackingApp.js

gdetracking.gweb.io/:241 GET
http://gdetracking.gweb.io/js/resources/angular-go

etc.....

**Comment by SmokyBob** [comment]
@brucemcpherson it's gweb.io...
For now please use the direct Google Drive URL
https://0ef5ddeb4723c66b72ceea3e2b8784165f179820.googledrive.com/host/0B_RClkFMLkcpeDdNSHVmVXdTY0k/#/

I'll start working on a GAE published version this evening

**Comment by patt0** [comment]
I have pushed the code to the staging environment so we can do some test.

http://elite-firefly-737.appspot.com/

First time authentication give some issues in the console, but once I
clicked on Sign In and authenticated myself it seemed to work.

Looks relatively fast, a few files are missing in git so they are giving
some errors in the console, but we will be able to check that quickly.

Bruce, do have look ( its on the staging database ) but maybe you can spot
some errors and give us some feedback.

Best



Patrick Martinent

**Comment by brucemcpherson** [comment]
Patrick

it all loads fine, and as you say it's only a few image files that are
missing now.

I noticed this in your .js ..

  //var ROOT = 'https://elite-firefly-737.appspot.com/_ah/api';
  var ROOT = 'https://omega-keep-406.appspot.com/_ah/api';

where ROOT is the 4th argument gapi.client.load .. but the load function
only takes 3 arguments ... so whatever you wanted to do with this is
probably not working

**Comment by Scarygami** [comment]
gapi.client.load takes a 4th argument, which is (unfortunately) undocumented in the client libary docs.

You will find it referred to in the endpoints docs:
https://cloud.google.com/appengine/docs/python/endpoints/consume_js

**Comment by brucemcpherson** [comment]
Gerwin thanks .. that's all new stuff to me, so I appreciate the pointer.

  i guess when running from the elite-firefly version as I am in this case,
the endpoint should match ?

 //var ROOT = 'https://elite-firefly-737.appspot.com/_ah/api';
  var ROOT = 'https://omega-keep-406.appspot.com/_ah/api';

apologies in advance if it's a dumb observation...

**Comment by Scarygami** [comment]
It basically points to different backend data.

The live data is hosted on omega-keep, so pointing the endpoint there makes the frontend work with the actual and not the test data, which I agree shouldn't be done for a testing environment.

We will probably host the actual frontend on gdetracking.appspot.com eventually, pointing to omega-keep for the backend.

**Comment by patt0** [comment]
I've deployed a change a while ago that points to the right place ...
 reload it it should point to the stage data.


Patrick Martinent
