### ISSUE TITLE
Removing ppl from tracking app

### ISSUE THREAD

**Issue by wojtek-kalicinski** [maiera/gde-app#197]
Is there a process for getting removed from the tracking app (at least from the email reminders)?
If not then I propose adding a way to unsubscribe for those of us who leave the program or don't want to get reminders, and could I please get manually removed for now? Thanks!

**Comment by patt0** [comment]
Yes we should be able to set your user to "inactive" in the backend, which
will exclude you from the process of harvesting new entries and updating
existing ones.

Let me know if you are ok with that and I will do it.





Patrick Martinent

**Comment by wojtek-kalicinski** [comment]
Yes please. Thanks!

**Comment by mauimauer** [comment]
Set to me inactive as well...thanks for the great time being a GDE :D

**Comment by patt0** [comment]
Done for both of you.


Patrick Martinent
