### ISSUE TITLE
GDE App not tracking my #gde posts

### ISSUE THREAD

**Issue by VictorSB** [maiera/gde-app#202]
I just posted a long list of #gde activities and none of them are showing in the gde tracking app.

There is about ten activities just posted on my google plus profile (https://plus.google.com/+V%C3%ADctorS%C3%A1nchezBelmar/posts).

Don't know if it helps but I am a new GDE added in the latest badge: https://developers.google.com/experts/people/v-ctor-s-nchez-belmar

**Comment by SmokyBob** [comment]
Discussed in the original G+ discussion why the activities were not tracked yesterday.
Checked seconds ago and 10 activities are stored backend.
Please check if everything is ok on your end on the web app, or let me know :)

**Comment by VictorSB** [comment]
It works, thanks again
