### ISSUE TITLE
Gde tracking app doesn't work for me

### ISSUE THREAD

**Issue by Janamou** [maiera/gde-app#203]
Hi, 
I am a GDE from January but the GDE tracking app is still not working for me (I don't see any of my activity, I am not mentioned etc.).
Can you please take a look at this?

Thank you :-)

**Comment by SmokyBob** [comment]
Checked and your account is missing.
I'll ask Ola to update create the account, after that, every public activity with #gde tag will be tracked.

I'll keep you posted on the status.

**Comment by Janamou** [comment]
Great, thank you!

**Comment by SmokyBob** [comment]
Account created so you should be able to see the "GDE Access" button.
Activities from the G+ Stream should be available tomorrow.
Let's wait till tomorrow to see if activities are imported correctly before closing the issue.

**Comment by SmokyBob** [comment]
@Janamou I see 2 activities were correctly imported

**Comment by Janamou** [comment]
Super, thanks again :-)
