### ISSUE TITLE
Only GDEs and admins may enter or change data

### ISSUE THREAD

**Issue by yenerm** [maiera/gde-app#204]
I can't edit my activities. 

![screen shot 2015-03-10 at 11 18 40 am](https://cloud.githubusercontent.com/assets/715370/6580340/999ceae2-c758-11e4-8ab2-ff6275e63b02.png)

The reason might be...
My plus account is murat.wave@gmail.com but I believe my gdgistanbul.com email might have been involved in some part.

**Comment by SmokyBob** [comment]
@yenerm Fixed the Email on the backend.
You should be able to update the activities now.
