### ISSUE TITLE
"How does it works?"

### ISSUE THREAD

**Issue by SmokyBob** [maiera/gde-app#209]
Lost in the mist of the activities this section was never updated and still says only "Soon!"

**Comment by Scarygami** [comment]
Also, should be called "How does it work?" for proper English :)

**Comment by SmokyBob** [comment]
:+1:

**Comment by SmokyBob** [comment]
Initial version available [here](https://github.com/SmokyBob/gde-app/commit/9da55dc134e50577717d1310c8a7e4597b9d151b) and live on the [staging environment](https://10-dot-gdetracking.appspot.com/)
@patt0 @Scarigami , let me know what you think should be added/ refrased, etc...

**Comment by patt0** [comment]
typo "series og jobs"

if you put it in a google doc, I can give a go at some more edits


Patrick Martinent

**Comment by SmokyBob** [comment]
Google Docs version available [here](https://docs.google.com/document/d/1UPInKbV6PDSemXpFUYVbGQ_DWdiME7LnEjfMhpD90U4/edit?usp=sharing) inside the GDE App TEAM folder on Google Drive.
Already fixed the typo and the fixes from @Scarygami in the commit

**Comment by SmokyBob** [comment]
Going to deploy in minutes, will fix it later if needed
