### ISSUE TITLE
Gather wider share metrics around urls using sharedcount.com API

### ISSUE THREAD

**Issue by mhawksey** [maiera/gde-app#21]
sharedcount.com have a handy api that aggregates shares/likes/+1s from a range of social networks and could be useful in collecting metrics around blog posts. You get 50,000 daily queries for free which should be plenty

**Comment by SmokyBob** [comment]
Moved to [new repo](https://github.com/GoogleDeveloperExperts/gde-app-backend/issues/9) and merged with another issue
