### ISSUE TITLE
Allow empty impact field

### ISSUE THREAD

**Issue by Scarygami** [maiera/gde-app#214]
Not every metadata necessarily needs to have impact assigned right away.
At the moment you get an ugly alert window that impact needs to be a valid integer.
You could also just default to "0" if no value has been entered.

**Comment by SmokyBob** [comment]
Sanity check got mixed up and defaulted the numeric values to 0 only if the value is numeric.

[This commit](https://github.com/maiera/gde-app/commit/31b4a6c24513925fc1ac0a863dc8b18386f1171e) fixes the problem.
Deploying in minutes with other fixes

**Comment by SmokyBob** [comment]
Deployed fix
