### ISSUE TITLE
Can't edit multiple metadata records

### ISSUE THREAD

**Issue by Scarygami** [maiera/gde-app#215]
It isn't possible to save the data for activities with multiple types correctly.

When switching between the metadata records the data stays the same, so everything you entered on the other types gets "forgotten".

Combined with https://github.com/maiera/gde-app/issues/214 this means you can't save the records, because you always get the warning popup for the other types.

**Comment by SmokyBob** [comment]
Seems a problem with the tab selection.
On it

**Comment by SmokyBob** [comment]
Deployed fix
