### ISSUE TITLE
GDEs "Options"

### ISSUE THREAD

**Issue by SmokyBob** [maiera/gde-app#217]
Add to the Web App an "options" section for GDEs so that they can edit/add userIds/URL/api_keys, etc... needed as we add more sources we harvest statistics/activities from.

Currently only for the SO Id (so_id).

This is way we can:
- Limit the effort maintaining the GDEs MasterList
- Let the GDEs choose if they want to use a source or not (if they don't want to they can remove the Id/URL/key)

**Comment by Scarygami** [comment]
Once we have decided on the fields we want to maintain, we will probably also have to adjust the Account model in the backend to store the options.

**Comment by SmokyBob** [comment]
@Scarygami Yes for sure.
At the moment in the staging env @patt0 added the `so_id` code [here](https://github.com/patt0/gde-app/commit/92a24713b921723d993f343397562a8ccf5183dc) and [here](https://github.com/patt0/gde-app/commit/aa5d9dcb2941390e24b13ad30decea87e8f4d990).
We "manually" updated the `so_id` with the infos collected for the Experts page to run some initial tests as #211 gets developed

**Comment by SmokyBob** [comment]
Moved
