### ISSUE TITLE
Scotland flag

### ISSUE THREAD

**Issue by SmokyBob** [maiera/gde-app#221]
Scotland flag is missing

**Comment by Scarygami** [comment]
Well... we don't have separate flags for England or Wales either...

**Comment by SmokyBob** [comment]
Now that you mention it.... I think it's because the country associated to
the GDE come from the manually input data on the old masterlist.

With the new Masterlist import, the country is the one that we get back
from the Google + API location + GEO location API... so we might get
different results.

Waiting after the new Masterlist data are pushed in staging before working
on this.

**Comment by SmokyBob** [comment]
Closing as the new Masterlist use Google Maps to get the country information
