### ISSUE TITLE
No My Activity Shows Up After Logged In

### ISSUE THREAD

**Issue by tyohan** [maiera/gde-app#222]
After i logged in with Google Account previously a new menu My Activity shows up on sidebar but now I can't get it. Console error below

`Failed to load resource: the server responded with a status of 403 (Forbidden)
plusLoginCtrl.js:59 Uncaught TypeError: Cannot read property 'people' of undefined
https://omega-keep-406.appspot.com/_ah/api/discovery/v1/apis/gdetracking/v1…/rest?fields=rootUrl%2CservicePath%2Cresources%2Cparameters%2Cmethods&pp=0 
Failed to load resource: the server responded with a status of 403 (Forbidden) GdeTrackingApp.js:34 `

`GdeApp Backend API LOADED!
angular.min.js:86 `

`TypeError: Cannot read property 'activity_type' of undefined
    at Object.$rootScope.utils.activityTypesFromApi (GdeTrackingApp.js:365)
    at GdeTrackingApp.js:432
    at h.$broadcast (angular.min.js:107)
    at GdeTrackingApp.js:37
    at h (apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en._HsXWPK6R0o.O/m=client,…=1/am=IQ/rs=AGLTcCNjg71BahpShZ9R_fIzIrho4mnrcg/t=zcms/cb=gapi.loaded_0:598)
    at apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en._HsXWPK6R0o.O/m=client,…=1/am=IQ/rs=AGLTcCNjg71BahpShZ9R_fIzIrho4mnrcg/t=zcms/cb=gapi.loaded_0:585
    at Object.<anonymous> (apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en._HsXWPK6R0o.O/m=client,…=1/am=IQ/rs=AGLTcCNjg71BahpShZ9R_fIzIrho4mnrcg/t=zcms/cb=gapi.loaded_0:169)
    at Object._.T.E.__cb (apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en._HsXWPK6R0o.O/m=client,…d=1/am=IQ/rs=AGLTcCNjg71BahpShZ9R_fIzIrho4mnrcg/t=zcms/cb=gapi.loaded_0:92)
    at g (apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en._HsXWPK6R0o.O/m=client,…d=1/am=IQ/rs=AGLTcCNjg71BahpShZ9R_fIzIrho4mnrcg/t=zcms/cb=gapi.loaded_0:86)
    at c (apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en._HsXWPK6R0o.O/m=client,…d=1/am=IQ/rs=AGLTcCNjg71BahpShZ9R_fIzIrho4mnrcg/t=zcms/cb=gapi.loaded_0:77)(anonymous function) @ angular.min.js:86
GdeTrackingApp.js:38 event emitted`

**Comment by SmokyBob** [comment]
Seems like we had some kind of problem on the backend during the WE.
Could you please check again?

I'll dig deeper in the possible causes later today

**Comment by tyohan** [comment]
Still can't access it. Also the console still show some error like above.

**Comment by patt0** [comment]
What url are you using to access it?

Can you try from another browser ... I checked all your data in the back
end and its pretty good.

Can you also try https://10-dot-gdetracking.appspot.com.

Thanks for your help.

Best


Patrick Martinent

**Comment by SmokyBob** [comment]
@patt0: Staging is most likely to be broken as I was pushing the changes form the new Masterlist.

@tyohan: have you tried from an Incognito window or another PC? Just to check if it's not some extension/flag causing the issue

**Comment by tyohan** [comment]
I'm using https://gdetracking.appspot.com/#/ the url that i got from G+ GDE Community page. Trying it on Chrome and Firefox but nothing works. On firefox even worst, only loading message i got and no menu or the map came. Still got errors like attached screenshot on Chrome. Can't use incognito, i'm currently abroad and Google authenticator doesn't work. 

![screen shot 2015-05-12 at 12 30 25 pm](https://cloud.githubusercontent.com/assets/106703/7580912/c815948e-f8a2-11e4-9b0b-29f4fa4d5d73.png)

**Comment by patt0** [comment]
May be a two factor authentication problem.

Are you using two factor?

Best

**Comment by tyohan** [comment]
I think it not a problem because, i use 2 factor but not have a problem with this before. Because it's handle by GAuth library. Will try with my Canary and if it's still have a problem.

**Comment by tyohan** [comment]
I got country blocking error when I try to access the API url directly from browser

https://elite-firefly-737.appspot.com/_ah/api/discovery/v1/apis/gdetracking/v1.0b2/rest?fields=rootUrl%2CservicePath%2Cresources%2Cparameters%2Cmethods&pp=0

I'm currently in Myanmar and I don't know why I can't use it from here. Will try to check it when I back to Indonesia.

**Comment by patt0** [comment]
Ok thanks

**Comment by tyohan** [comment]
Confirmed, it works after I'm back to Indonesia. Case closed.
