### ISSUE TITLE
Adding new activity should show success message

### ISSUE THREAD

**Issue by zmandel** [maiera/gde-app#225]
When a new activity is entered, there is no confirmation that the activity was actually saved. I just saved one and it

1) didnt show any message about a succesful save, and 
2) the new activity didnt show in the list shown after entering the activity.

refreshing the page to refresh the activity table is not a solution because currently that logs you out and takes you back to the home page which logs you in again after a few seconds. You then need to click "gde access" again.

**Comment by SmokyBob** [comment]
Move to [new repo](https://github.com/GoogleDeveloperExperts/gde-app-web/issues/9)
