### ISSUE TITLE
Sending emails to non authenticated users.

### ISSUE THREAD

**Issue by LindaLawton** [maiera/gde-app#229]
Back in December I removed access to the tracking app from my Google Account.  There should be no access associated with me.  

Why are you sending emails to no authenticated users?  Shouldn't you have stopped scanning me?  I have removed the #gde tag on that post will the system remove it?

------------------------------------------------------------------------------------------
The GDE Tracking team thanks you for using the tool.

The following post(s) is(are) missing Activity Type and/or Product Group hashtags. Because of this, it(they) does not reflect in your GDE stats.

https://plus.google.com/+LindaLawton/posts/2GumZxRGyin

Kindly update your post(s) with #hashtags. A reminder of the valid hashtags can be found in the 'How Its Used?' section of http://gdetracking.gweb.io/.

GDE Tracking Team

------------------------------------------------------------------------------------------

**Comment by SmokyBob** [comment]
Google + Public stream is searched for each Technology Google Expert that is present in the Expert MasterList and have a Google + Id.
The scan task is not bound to authorization, search is done on public Google + stream and emails are sent to the email address provided in the Expert MasterList.

Not 100% sure if removing the #gde tag will remove the tracking of the activity.

**Comment by Scarygami** [comment]
Posts that have been edited to remove the #gde tag will be ignored from then on.

**Comment by LindaLawton** [comment]
OK thanks seriously need to remember never to use that tag.

**Comment by SmokyBob** [comment]
[New tag](https://github.com/GoogleDeveloperExperts/gde-app-backend/issues/2) will be tracked in the near future.
Moved discussion to the new repo
