### ISSUE TITLE
Unable to create/edit activities in GDE tracking app

### ISSUE THREAD

**Issue by dalehumby** [maiera/gde-app#230]
Since about the start of the year I have not been able to create any new activities in the GDE tracking app.

I can log in fine (dalehumby@gmail.com), and can see the activities that I have already created, but cannot edit/create activities. If I try, I see the following error "Only GDEs and admins may enter or change data." (see below screenshot.)

![image](https://cloud.githubusercontent.com/assets/5817143/8129995/3e0689ee-110f-11e5-9e37-6cf38a28da96.png)

My G+ (login) is dalehumby@gmail.com, and the email I get GDE emails to is dale@nomanini.com.

Thanks
Dale

**Comment by SmokyBob** [comment]
Sorry to get back at you so late.
Manually fixed the data on the backend so you should be able to login without any problem.

**Comment by SmokyBob** [comment]
@dalehumby : ping

**Comment by Scarygami** [comment]
Created an issue in the new repo that should prevent such problems in the future:
https://github.com/GoogleDeveloperExperts/gde-app-backend/issues/1

Need to discuss this approach with Nathalie and @patt0 first though.

**Comment by dalehumby** [comment]
Thanks, all working now. Can edit and create events. Thanks for fixing.
