### ISSUE TITLE
Import historic data from GDE activity web form(s)

### ISSUE THREAD

**Issue by maiera** [maiera/gde-app#35]
There are two sets of historic GDE activity tracking data, which need to be imported into the app.

GDE Activity Tracking V2 -- most recent, used until end of Q2
https://drive.google.com/open?id=0As4qk14rHviTdE9STy1Sa181clMzNnEyelNodlp6aXc&authuser=0

GDE Activity Tracking V1 -- last used in 2013
https://docs.google.com/a/google.com/spreadsheet/ccc?key=0As4qk14rHviTdHpxMnMtWmNEb253cjFjODA3OVlUbGc#gid=0

**Comment by SmokyBob** [comment]
Moved to the new repo in this [issue](https://github.com/GoogleDeveloperExperts/gde-app-backend/issues/5)
