### ISSUE TITLE
Unused Polymer Components

### ISSUE THREAD

**Issue by reicek** [maiera/gde-app#57]
Many of the Components in the folder are not actually being used, the folder was filled with almost everything to make initial development easier but it's time to clean it up.

**Comment by SmokyBob** [comment]
A bit later than expected but I've almost finished upgrading to Polymer 0.5.2 and cleaning the dependencies.
[Live demo](https://gdetracking.gweb.io/hist/mauro/issue57/)
[Pre Pull Repo](https://github.com/SmokyBob/gde-app/tree/iss57)

The changes are quite a bit, the site loads a bit faster (a couple of elements less to load), and most of the UI works as expected on desktop/tablet and phone, just a couple of things are left to fix.
Going to give the final touches in the next days, cleaning up a bit the code and replacing a couple of other elements with webcomponents.

**Comment by reicek** [comment]
Awesome Gerwin! =) great contribution.

+1 to vulcanize the dependencies,

*César Antón Dorantes*
*______________________*
Developer @ mejorando.la <https://mejorando.la/>
Google Developer Expert <https://developers.google.com/experts/+CesarAnton>
*Technical Writer <http://cesarstechinsights.blogspot.com>*

2015-01-03 2:01 GMT-05:00 Mauro Solcia <notifications@github.com>:

**Comment by SmokyBob** [comment]
Updated the last little things like paper-shadow and /deep/ on prettyTable css to be correctly used in dialogs.

Re tested on tablet and phones... 
On the phone edit is still almost impossible, even in landscape mode.
On a 7'' tablet, a couple of visual artifacts on scrollbars, but  mostly usable.

Playing around with the [google-chart](https://github.com/GoogleWebComponents/google-chart) component to see if the code gets a bit cleaner.
