### ISSUE TITLE
Google Analytics tracking

### ISSUE THREAD

**Issue by reicek** [maiera/gde-app#69]
Google Analytics provides an almost universal and reliable way for the GDE Tracking App to gather non g+ impact metada. This will also allow us to add the pageViews metric into the reports.

Did a little research and it seems we need the following information from the user:

* The ID of the Analytics account.

* The relative path to the publishing (this can be taken from another field)
* The start-date (this can be taken from another field)
* The end-date (this can be taken from the system's current date)

So pretty much the user would only need to provide the ID of the Analitycs account being used on the site were the activity was published.

For example, this query would return the updated visits count for the first year of my last article:

https://www.googleapis.com/analytics/v3/data/ga?
ids=ga%3A70930571
&metrics=ga%3Apageviews
&filters=ga%3ApagePath%3D%3D%2F2014%2F08%2FFirebaseHTMLChat.html
&start-date=2014-08-13
&end-date=2014-08-14 

More information:
https://developers.google.com/analytics/devguides/reporting/core/v3/reference

Google Analytics Query Explorer 2:
http://ga-dev-tools.appspot.com/explorer/

**Comment by SmokyBob** [comment]
Moved to [new repo](https://github.com/GoogleDeveloperExperts/gde-app-backend/issues/9) and merged with another issue
