### ISSUE TITLE
Breakdown/Statistic Methods for the API

### ISSUE THREAD

**Issue by mauimauer** [maiera/gde-app#80]
Provide some methods that provide numerical breakdowns/cumulative stats of the metrics collected by the Activity Tracker (Activity count, Reshares/+1s etc.). As of today the Web App generates those values by actually processing the full records, potentially wasting bandwidth if the user just wants a quick glance at his/her stat charts.

Having those methods could also help to keep the required Bandwidth for the Android App at a minimum, by only having to request records if the user wants to specifically look at them.

(Maybe add a fields parameter to the full record routes as well to allow requesting specific sets of fields instead of transferring the whole record)

**Comment by SmokyBob** [comment]
Moved
