### ISSUE TITLE
Make ActivityRecords deletable

### ISSUE THREAD

**Issue by Scarygami** [maiera/gde-app#99]
This will only be implemented as a flag, and not a full delete in the datastore.

AR.list will by default only return non-deleted entities for reports, with a query-param to show all.

In the update task if all AP posts have been deleted from an AR, the AR will be flagged as deleted automatically.
To be decided: what happens if a previously deleted AR gets a new AP post coming in?

**Comment by SmokyBob** [comment]
@LindaLawton Test version is up [here](http://gdetracking.gweb.io/hist/mauro/issue99/) delete/trash/untrash are in place.
Waiting 48hrs before merging in the main branch.

**Comment by SmokyBob** [comment]
Deployed
